# Uncomment this line to define a global platform for your projectplatform :ios, '6.0'

use_frameworks!

plugin 'cocoapods-keys', {
  :project => "BarRoulette",
  :keys => [
  	"UberClientId",
  	"UberClientSecret",
  	"UberServerToken",
  	"YelpkConsumerKey",
  	"YelpkConsumerSecret",
  	"YelpkToken",
  	"YelpkTokenSecret"
  ]}

target 'BarRoulette' do


  pod "Uber-iOS-SDK"
  pod 'p2.OAuth2', '~> 2.0'

end

target 'BarRouletteTests' do

end
